# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: tenju-ubuntu-vm

variables:
  COVERITY_TOOL_HOME: '/opt/cov-analysis’

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export PATH=$PATH:$COVERITY_TOOL_HOME/bin
      set -x
      cov-configure --java