# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: tenju-ubuntu-vm


steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export PATH=$PATH:/opt/cov-analysis/bin
      set -x
      cov-configure --java
      cov-build --dir idir ./gradlew clean build -x :spotlessYamlCheck
      cov-analyze --dir idir --all --webapp-security --distrust-all --strip-path $(Build.SourcesDirectory)
  displayName: 'Coverity' 